### ISSUE TITLE
Cannot generate synthetic dataset

### ISSUE THREAD

**Issue by Yuliang-Zou** [shubhtuls/mvcSnP#1] opened 2018-02-02 00:17 UTC
Hi @shubhtuls , thanks for the code. But I have some problems generating the dataset:

1. I am using Python3.6 instead of Python2.7. So I used _pickle instead of cPickle in `renderPreprocessShapenet.py`. But I got error in Line46 of this file: "TypeError: can't pickle dict_key objects". I found that this line might be ignored, so I comment it and keep running the code.

2. I also found that in Line263 of `renderer/render_model_views.py`, ` rl.outputs` doesn't have the key 'Z', I replace it with 'Depth'. I wonder if this is the version problem. I used the latest 2.79 version of blender. And I download the shapnet models using `http://shapenet.cs.stanford.edu/shapenet/obj-zip/ShapeNetCore.v1/<synsetId>.zip` (I only downloaded the 3 categories used in the paper).

3. Later I found that my render_x.png are all black pixels. I then check the .exr file, the rgb channels are all 0 values. Not sure what's the problem.

4. I am not familiar with blender, I wonder if it can also generate surface normal output.

Thanks!

**Comment by shubhtuls** [comment] 2018-02-02 02:12
Hi,
Thanks for the queries. I'm not entirely sure why you do not get renderings, since the released preprocessing code is basically the same as that in a [previous project](https://github.com/shubhtuls/drc) which several people have reported re-using.

As a possible debugging step, I'd recommend reading the outputs of the blender rendering script (maybe it can't find the models and some paths may be off). Additionally, it might be useful to see if the rendering script works in a setup similar to mine (python 2.7 and Blender 2.71).

Lastly, you can consider computing gradients of the rendered depth to infer normal maps. I'm not sure if it's easy to extract them via blender.

**Comment by Yuliang-Zou** [comment] 2018-02-02 02:47
Thanks for the reply.
Just double check the code, I found that the RGB channels in the generated exr file have all 0 zeros. Still trying to figure out the reason.

**Comment by shubhtuls** [comment] 2018-02-02 03:55
I'm sorry but I can't reproduce this bug on my end. I made a fresh clone of the released code and ran the rendering script on my machine, and it seems to work.

**Comment by Yuliang-Zou** [comment] 2018-02-05 19:59
Hi @shubhtuls , I notice that in line25 of `renderer/render_model_views.py`, you set `g_syn_light_num_highbound = 0`. But you've already cleared the default light, seems that there will be no point light either. So in this case, it might cause all black?

**Comment by shubhtuls** [comment] 2018-02-05 21:36
Hi @Yuliang-Zou ,
Yes, line 25 means that there will be no point lights. But, we specify some environment light [here](https://github.com/shubhtuls/mvcSnP/blob/master/preprocess/synthetic/rendering/renderer/render_model_views.py#L34-L35) and use those [here](https://github.com/shubhtuls/mvcSnP/blob/master/preprocess/synthetic/rendering/renderer/render_model_views.py#L311-L315) so the renderings should not be all black.

**Comment by B1ueber2y** [comment] 2018-04-08 07:36
Hi @Yuliang-Zou ,
Have you solved the problem? I run the code with blender 2.79 and got blank rendering as well. The depth output was fine. I am wondering if there is a version problem.

Thanks!

**Comment by Yuliang-Zou** [comment] 2018-04-08 19:46
@B1ueber2y You can set a non-zero number in line25 of `renderer/render_model_views.py`, then you will get some meaningful RGB output. But I don't know what the performance will be if you use this setting.

**Comment by B1ueber2y** [comment] 2018-04-09 02:55
@Yuliang-Zou 
Thanks a lot. I found that the code works with blender 2.71. I downloaded the previous version and got meaningful outputs.

**Comment by shubhtuls** [comment] 2018-05-26 23:17
Thanks for the discussion here. Closing this as using blender 2.71 seems to resolve the issue.

**Closed as completed by shubhtuls** 2018-05-26 23:17 UTC
